# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\B62427\Documents\lidsim\src\gui\QtDMainForm.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(494, 637)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../images/logos/lidsimicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setDockNestingEnabled(True)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowNestedDocks|QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks|QtWidgets.QMainWindow.GroupedDragging)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_1 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_1.setObjectName("groupBox_1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.comboBox_SelectedPredeterminedLidar = QtWidgets.QComboBox(self.groupBox_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_SelectedPredeterminedLidar.sizePolicy().hasHeightForWidth())
        self.comboBox_SelectedPredeterminedLidar.setSizePolicy(sizePolicy)
        self.comboBox_SelectedPredeterminedLidar.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.comboBox_SelectedPredeterminedLidar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.comboBox_SelectedPredeterminedLidar.setMaxVisibleItems(3)
        self.comboBox_SelectedPredeterminedLidar.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.comboBox_SelectedPredeterminedLidar.setMinimumContentsLength(7)
        self.comboBox_SelectedPredeterminedLidar.setObjectName("comboBox_SelectedPredeterminedLidar")
        self.gridLayout_4.addWidget(self.comboBox_SelectedPredeterminedLidar, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_1)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_4)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_11 = QtWidgets.QLabel(self.groupBox_1)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_9.addWidget(self.label_11)
        self.lineEdit_lidarName = QtWidgets.QLineEdit(self.groupBox_1)
        self.lineEdit_lidarName.setObjectName("lineEdit_lidarName")
        self.horizontalLayout_9.addWidget(self.lineEdit_lidarName)
        self.label_13 = QtWidgets.QLabel(self.groupBox_1)
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_9.addWidget(self.label_13)
        self.label_2 = QtWidgets.QLabel(self.groupBox_1)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_9.addWidget(self.label_2)
        self.comboBox_lidarKind = QtWidgets.QComboBox(self.groupBox_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_lidarKind.sizePolicy().hasHeightForWidth())
        self.comboBox_lidarKind.setSizePolicy(sizePolicy)
        self.comboBox_lidarKind.setObjectName("comboBox_lidarKind")
        self.comboBox_lidarKind.addItem("")
        self.comboBox_lidarKind.addItem("")
        self.horizontalLayout_9.addWidget(self.comboBox_lidarKind)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.label_17 = QtWidgets.QLabel(self.groupBox_1)
        self.label_17.setObjectName("label_17")
        self.verticalLayout.addWidget(self.label_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_19 = QtWidgets.QLabel(self.groupBox_1)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_18.addWidget(self.label_19)
        self.lineEdit_minRange = QtWidgets.QLineEdit(self.groupBox_1)
        self.lineEdit_minRange.setObjectName("lineEdit_minRange")
        self.horizontalLayout_18.addWidget(self.lineEdit_minRange)
        self.label_21 = QtWidgets.QLabel(self.groupBox_1)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_18.addWidget(self.label_21)
        self.lineEdit_maxRange = QtWidgets.QLineEdit(self.groupBox_1)
        self.lineEdit_maxRange.setObjectName("lineEdit_maxRange")
        self.horizontalLayout_18.addWidget(self.lineEdit_maxRange)
        self.label_22 = QtWidgets.QLabel(self.groupBox_1)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_18.addWidget(self.label_22)
        self.lineEdit_rangeSTD = QtWidgets.QLineEdit(self.groupBox_1)
        self.lineEdit_rangeSTD.setObjectName("lineEdit_rangeSTD")
        self.horizontalLayout_18.addWidget(self.lineEdit_rangeSTD)
        self.verticalLayout.addLayout(self.horizontalLayout_18)
        self.label_42 = QtWidgets.QLabel(self.groupBox_1)
        self.label_42.setObjectName("label_42")
        self.verticalLayout.addWidget(self.label_42)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.label_47 = QtWidgets.QLabel(self.groupBox_1)
        self.label_47.setObjectName("label_47")
        self.horizontalLayout_34.addWidget(self.label_47)
        self.lineEdit_horizontalResolution = QtWidgets.QLineEdit(self.groupBox_1)
        self.lineEdit_horizontalResolution.setObjectName("lineEdit_horizontalResolution")
        self.horizontalLayout_34.addWidget(self.lineEdit_horizontalResolution)
        self.label_48 = QtWidgets.QLabel(self.groupBox_1)
        self.label_48.setObjectName("label_48")
        self.horizontalLayout_34.addWidget(self.label_48)
        self.lineEdit_verticalResolution = QtWidgets.QLineEdit(self.groupBox_1)
        self.lineEdit_verticalResolution.setObjectName("lineEdit_verticalResolution")
        self.horizontalLayout_34.addWidget(self.lineEdit_verticalResolution)
        self.verticalLayout.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.label_49 = QtWidgets.QLabel(self.groupBox_1)
        self.label_49.setObjectName("label_49")
        self.horizontalLayout_35.addWidget(self.label_49)
        self.lineEdit_horizontalAccuracy = QtWidgets.QLineEdit(self.groupBox_1)
        self.lineEdit_horizontalAccuracy.setObjectName("lineEdit_horizontalAccuracy")
        self.horizontalLayout_35.addWidget(self.lineEdit_horizontalAccuracy)
        self.label_50 = QtWidgets.QLabel(self.groupBox_1)
        self.label_50.setObjectName("label_50")
        self.horizontalLayout_35.addWidget(self.label_50)
        self.lineEdit_verticalAccuracy = QtWidgets.QLineEdit(self.groupBox_1)
        self.lineEdit_verticalAccuracy.setObjectName("lineEdit_verticalAccuracy")
        self.horizontalLayout_35.addWidget(self.lineEdit_verticalAccuracy)
        self.verticalLayout.addLayout(self.horizontalLayout_35)
        self.label_43 = QtWidgets.QLabel(self.groupBox_1)
        self.label_43.setObjectName("label_43")
        self.verticalLayout.addWidget(self.label_43)
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.label_46 = QtWidgets.QLabel(self.groupBox_1)
        self.label_46.setObjectName("label_46")
        self.horizontalLayout_36.addWidget(self.label_46)
        self.lineEdit_horizontalFOV = QtWidgets.QLineEdit(self.groupBox_1)
        self.lineEdit_horizontalFOV.setCursorPosition(0)
        self.lineEdit_horizontalFOV.setObjectName("lineEdit_horizontalFOV")
        self.horizontalLayout_36.addWidget(self.lineEdit_horizontalFOV)
        self.label_52 = QtWidgets.QLabel(self.groupBox_1)
        self.label_52.setObjectName("label_52")
        self.horizontalLayout_36.addWidget(self.label_52)
        self.lineEdit_verticalFOV = QtWidgets.QLineEdit(self.groupBox_1)
        self.lineEdit_verticalFOV.setObjectName("lineEdit_verticalFOV")
        self.horizontalLayout_36.addWidget(self.lineEdit_verticalFOV)
        self.label_53 = QtWidgets.QLabel(self.groupBox_1)
        self.label_53.setObjectName("label_53")
        self.horizontalLayout_36.addWidget(self.label_53)
        self.lineEdit_lidarFPS = QtWidgets.QLineEdit(self.groupBox_1)
        self.lineEdit_lidarFPS.setMaximumSize(QtCore.QSize(16777213, 16777215))
        self.lineEdit_lidarFPS.setCursorPosition(0)
        self.lineEdit_lidarFPS.setObjectName("lineEdit_lidarFPS")
        self.horizontalLayout_36.addWidget(self.lineEdit_lidarFPS)
        self.verticalLayout.addLayout(self.horizontalLayout_36)
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.pushButton_loadLidarConfig = QtWidgets.QPushButton(self.groupBox_1)
        self.pushButton_loadLidarConfig.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton_loadLidarConfig.setToolTipDuration(0)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../images/icons/green_arrow_down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_loadLidarConfig.setIcon(icon1)
        self.pushButton_loadLidarConfig.setObjectName("pushButton_loadLidarConfig")
        self.horizontalLayout_42.addWidget(self.pushButton_loadLidarConfig)
        self.pushButton_saveLidarConfig = QtWidgets.QPushButton(self.groupBox_1)
        self.pushButton_saveLidarConfig.setToolTipDuration(0)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../images/icons/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_saveLidarConfig.setIcon(icon2)
        self.pushButton_saveLidarConfig.setObjectName("pushButton_saveLidarConfig")
        self.horizontalLayout_42.addWidget(self.pushButton_saveLidarConfig)
        self.verticalLayout.addLayout(self.horizontalLayout_42)
        self.gridLayout_3.addWidget(self.groupBox_1, 0, 0, 2, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.groupBox_2.setStyleSheet("QWidget#groupBox{\n"
"border: 1px solid; \n"
"border-radius: 1px;\n"
"\n"
"}")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.lineEdit_objectFile = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_objectFile.setObjectName("lineEdit_objectFile")
        self.horizontalLayout.addWidget(self.lineEdit_objectFile)
        self.toolButton_ChangeObjectFile = QtWidgets.QToolButton(self.groupBox_2)
        self.toolButton_ChangeObjectFile.setObjectName("toolButton_ChangeObjectFile")
        self.horizontalLayout.addWidget(self.toolButton_ChangeObjectFile)
        self.verticalLayout_17.addLayout(self.horizontalLayout)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.horizontalLayout_12.addWidget(self.label)
        self.lineEdit_trajectoryFile = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_trajectoryFile.setObjectName("lineEdit_trajectoryFile")
        self.horizontalLayout_12.addWidget(self.lineEdit_trajectoryFile)
        self.toolButton_ChangeTrajectoryFile = QtWidgets.QToolButton(self.groupBox_2)
        self.toolButton_ChangeTrajectoryFile.setObjectName("toolButton_ChangeTrajectoryFile")
        self.horizontalLayout_12.addWidget(self.toolButton_ChangeTrajectoryFile)
        self.verticalLayout_17.addLayout(self.horizontalLayout_12)
        self.label_44 = QtWidgets.QLabel(self.groupBox_2)
        self.label_44.setObjectName("label_44")
        self.verticalLayout_17.addWidget(self.label_44)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.label_20 = QtWidgets.QLabel(self.groupBox_2)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_33.addWidget(self.label_20)
        self.lineEdit_animationFPS = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_animationFPS.setObjectName("lineEdit_animationFPS")
        self.horizontalLayout_33.addWidget(self.lineEdit_animationFPS)
        self.label_45 = QtWidgets.QLabel(self.groupBox_2)
        self.label_45.setObjectName("label_45")
        self.horizontalLayout_33.addWidget(self.label_45)
        self.lineEdit_animationElevation = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_animationElevation.setObjectName("lineEdit_animationElevation")
        self.horizontalLayout_33.addWidget(self.lineEdit_animationElevation)
        self.label_51 = QtWidgets.QLabel(self.groupBox_2)
        self.label_51.setObjectName("label_51")
        self.horizontalLayout_33.addWidget(self.label_51)
        self.lineEdit_animationAzimuth = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_animationAzimuth.setObjectName("lineEdit_animationAzimuth")
        self.horizontalLayout_33.addWidget(self.lineEdit_animationAzimuth)
        self.checkBox_animationHideAxis = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_animationHideAxis.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_animationHideAxis.setObjectName("checkBox_animationHideAxis")
        self.horizontalLayout_33.addWidget(self.checkBox_animationHideAxis)
        self.checkBox_animationShowLidar = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_animationShowLidar.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_animationShowLidar.setObjectName("checkBox_animationShowLidar")
        self.horizontalLayout_33.addWidget(self.checkBox_animationShowLidar)
        self.verticalLayout_17.addLayout(self.horizontalLayout_33)
        self.label_58 = QtWidgets.QLabel(self.groupBox_2)
        self.label_58.setObjectName("label_58")
        self.verticalLayout_17.addWidget(self.label_58)
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.label_23 = QtWidgets.QLabel(self.groupBox_2)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_37.addWidget(self.label_23)
        self.lineEdit_boundxmin = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_boundxmin.setObjectName("lineEdit_boundxmin")
        self.horizontalLayout_37.addWidget(self.lineEdit_boundxmin)
        self.label_25 = QtWidgets.QLabel(self.groupBox_2)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_37.addWidget(self.label_25)
        self.lineEdit_boundymin = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_boundymin.setObjectName("lineEdit_boundymin")
        self.horizontalLayout_37.addWidget(self.lineEdit_boundymin)
        self.label_27 = QtWidgets.QLabel(self.groupBox_2)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_37.addWidget(self.label_27)
        self.lineEdit_boundzmin = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_boundzmin.setObjectName("lineEdit_boundzmin")
        self.horizontalLayout_37.addWidget(self.lineEdit_boundzmin)
        self.verticalLayout_17.addLayout(self.horizontalLayout_37)
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.label_24 = QtWidgets.QLabel(self.groupBox_2)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_40.addWidget(self.label_24)
        self.lineEdit_boundxmax = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_boundxmax.setObjectName("lineEdit_boundxmax")
        self.horizontalLayout_40.addWidget(self.lineEdit_boundxmax)
        self.label_26 = QtWidgets.QLabel(self.groupBox_2)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_40.addWidget(self.label_26)
        self.lineEdit_boundymax = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_boundymax.setObjectName("lineEdit_boundymax")
        self.horizontalLayout_40.addWidget(self.lineEdit_boundymax)
        self.label_28 = QtWidgets.QLabel(self.groupBox_2)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_40.addWidget(self.label_28)
        self.lineEdit_boundzmax = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_boundzmax.setObjectName("lineEdit_boundzmax")
        self.horizontalLayout_40.addWidget(self.lineEdit_boundzmax)
        self.verticalLayout_17.addLayout(self.horizontalLayout_40)
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.pushButton_loadScenario = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_loadScenario.setToolTipDuration(0)
        self.pushButton_loadScenario.setIcon(icon1)
        self.pushButton_loadScenario.setObjectName("pushButton_loadScenario")
        self.horizontalLayout_39.addWidget(self.pushButton_loadScenario)
        self.pushButton_launchAnimation = QtWidgets.QPushButton(self.groupBox_2)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../images/icons/view_3D.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_launchAnimation.setIcon(icon3)
        self.pushButton_launchAnimation.setObjectName("pushButton_launchAnimation")
        self.horizontalLayout_39.addWidget(self.pushButton_launchAnimation)
        self.pushButton_launchCharts = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_launchCharts.setToolTipDuration(0)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../images/icons/target.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_launchCharts.setIcon(icon4)
        self.pushButton_launchCharts.setObjectName("pushButton_launchCharts")
        self.horizontalLayout_39.addWidget(self.pushButton_launchCharts)
        self.verticalLayout_17.addLayout(self.horizontalLayout_39)
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.lineEdit_saveAnimationFilename = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_saveAnimationFilename.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_saveAnimationFilename.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_saveAnimationFilename.setObjectName("lineEdit_saveAnimationFilename")
        self.horizontalLayout_38.addWidget(self.lineEdit_saveAnimationFilename)
        self.pushButton_saveAnimation = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_saveAnimation.setToolTipDuration(0)
        self.pushButton_saveAnimation.setIcon(icon2)
        self.pushButton_saveAnimation.setObjectName("pushButton_saveAnimation")
        self.horizontalLayout_38.addWidget(self.pushButton_saveAnimation)
        self.lineEdit_saveTrajectoryFilename = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_saveTrajectoryFilename.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_saveTrajectoryFilename.setObjectName("lineEdit_saveTrajectoryFilename")
        self.horizontalLayout_38.addWidget(self.lineEdit_saveTrajectoryFilename)
        self.pushButton_saveTrajectory = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_saveTrajectory.setToolTipDuration(0)
        self.pushButton_saveTrajectory.setIcon(icon2)
        self.pushButton_saveTrajectory.setObjectName("pushButton_saveTrajectory")
        self.horizontalLayout_38.addWidget(self.pushButton_saveTrajectory)
        self.verticalLayout_17.addLayout(self.horizontalLayout_38)
        self.gridLayout_3.addWidget(self.groupBox_2, 2, 0, 1, 1)
        self.label_Status = QtWidgets.QLabel(self.centralwidget)
        self.label_Status.setLineWidth(17)
        self.label_Status.setObjectName("label_Status")
        self.gridLayout_3.addWidget(self.label_Status, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 494, 21))
        self.menubar.setObjectName("menubar")
        self.menuJobs = QtWidgets.QMenu(self.menubar)
        self.menuJobs.setObjectName("menuJobs")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionEdit_List = QtWidgets.QAction(MainWindow)
        self.actionEdit_List.setIcon(icon2)
        self.actionEdit_List.setObjectName("actionEdit_List")
        self.actionLaunch = QtWidgets.QAction(MainWindow)
        self.actionLaunch.setObjectName("actionLaunch")
        self.actionLaunch_List = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../images/icons/next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLaunch_List.setIcon(icon5)
        self.actionLaunch_List.setObjectName("actionLaunch_List")
        self.actionEdit_Job = QtWidgets.QAction(MainWindow)
        self.actionEdit_Job.setObjectName("actionEdit_Job")
        self.actionLaunch_Job = QtWidgets.QAction(MainWindow)
        self.actionLaunch_Job.setObjectName("actionLaunch_Job")
        self.actionTemplate_Path = QtWidgets.QAction(MainWindow)
        self.actionTemplate_Path.setEnabled(False)
        self.actionTemplate_Path.setObjectName("actionTemplate_Path")
        self.actionShow_Hide_Video_Window = QtWidgets.QAction(MainWindow)
        self.actionShow_Hide_Video_Window.setEnabled(False)
        self.actionShow_Hide_Video_Window.setObjectName("actionShow_Hide_Video_Window")
        self.actionlocal_mode = QtWidgets.QAction(MainWindow)
        self.actionlocal_mode.setEnabled(False)
        self.actionlocal_mode.setObjectName("actionlocal_mode")
        self.actionNew_Session = QtWidgets.QAction(MainWindow)
        self.actionNew_Session.setObjectName("actionNew_Session")
        self.actionOpen_Session = QtWidgets.QAction(MainWindow)
        self.actionOpen_Session.setEnabled(True)
        self.actionOpen_Session.setIcon(icon1)
        self.actionOpen_Session.setObjectName("actionOpen_Session")
        self.actionSave_Session_As = QtWidgets.QAction(MainWindow)
        self.actionSave_Session_As.setIcon(icon2)
        self.actionSave_Session_As.setObjectName("actionSave_Session_As")
        self.actionPath_Root = QtWidgets.QAction(MainWindow)
        self.actionPath_Root.setObjectName("actionPath_Root")
        self.actionSession_Manager = QtWidgets.QAction(MainWindow)
        self.actionSession_Manager.setObjectName("actionSession_Manager")
        self.actionChange_lidar_file = QtWidgets.QAction(MainWindow)
        self.actionChange_lidar_file.setObjectName("actionChange_lidar_file")
        self.actionChange_save_folder = QtWidgets.QAction(MainWindow)
        self.actionChange_save_folder.setObjectName("actionChange_save_folder")
        self.actionViewing_parameters = QtWidgets.QAction(MainWindow)
        self.actionViewing_parameters.setObjectName("actionViewing_parameters")
        self.menuJobs.addAction(self.actionChange_lidar_file)
        self.menuJobs.addAction(self.actionChange_save_folder)
        self.menuJobs.addSeparator()
        self.menuJobs.addAction(self.actionViewing_parameters)
        self.menubar.addAction(self.menuJobs.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.comboBox_SelectedPredeterminedLidar, self.lineEdit_objectFile)
        MainWindow.setTabOrder(self.lineEdit_objectFile, self.toolButton_ChangeObjectFile)
        MainWindow.setTabOrder(self.toolButton_ChangeObjectFile, self.lineEdit_trajectoryFile)
        MainWindow.setTabOrder(self.lineEdit_trajectoryFile, self.toolButton_ChangeTrajectoryFile)
        MainWindow.setTabOrder(self.toolButton_ChangeTrajectoryFile, self.lineEdit_lidarName)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LidSim"))
        self.groupBox_1.setTitle(_translate("MainWindow", "Lidar"))
        self.label_9.setText(_translate("MainWindow", "Lidar model:"))
        self.label_11.setText(_translate("MainWindow", "Name:"))
        self.label_2.setText(_translate("MainWindow", "Kind:"))
        self.comboBox_lidarKind.setItemText(0, _translate("MainWindow", "flash"))
        self.comboBox_lidarKind.setItemText(1, _translate("MainWindow", "scanning"))
        self.label_17.setText(_translate("MainWindow", "Range parameters (m):"))
        self.label_19.setText(_translate("MainWindow", "Minimum:"))
        self.label_21.setText(_translate("MainWindow", "Maximum:"))
        self.label_22.setText(_translate("MainWindow", "Standard deviation:"))
        self.label_42.setText(_translate("MainWindow", "Angular parameters (degrees):"))
        self.label_47.setText(_translate("MainWindow", "Horizontal resolution:"))
        self.label_48.setText(_translate("MainWindow", "Vertical resolution:"))
        self.label_49.setText(_translate("MainWindow", "Horizontal accuracy:"))
        self.label_50.setText(_translate("MainWindow", "Vertical accuracy:"))
        self.label_43.setText(_translate("MainWindow", "Coverage parameters:"))
        self.label_46.setText(_translate("MainWindow", "Horizontal FOV:"))
        self.label_52.setText(_translate("MainWindow", "Vertical FOV:"))
        self.label_53.setText(_translate("MainWindow", "Frame rate:"))
        self.pushButton_loadLidarConfig.setText(_translate("MainWindow", "Load lidar"))
        self.pushButton_saveLidarConfig.setText(_translate("MainWindow", "Save lidar"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Scenario"))
        self.label_7.setText(_translate("MainWindow", "Object file:"))
        self.toolButton_ChangeObjectFile.setText(_translate("MainWindow", "..."))
        self.label.setText(_translate("MainWindow", "Trajectory file:"))
        self.toolButton_ChangeTrajectoryFile.setText(_translate("MainWindow", "..."))
        self.label_44.setText(_translate("MainWindow", "Camera parameters:"))
        self.label_20.setText(_translate("MainWindow", "FPS:"))
        self.label_45.setText(_translate("MainWindow", "Elevation:"))
        self.label_51.setText(_translate("MainWindow", "Azimuth:"))
        self.checkBox_animationHideAxis.setText(_translate("MainWindow", "Hide axis"))
        self.checkBox_animationShowLidar.setText(_translate("MainWindow", "Show lidar"))
        self.label_58.setText(_translate("MainWindow", "Camera bounding (m):"))
        self.label_23.setText(_translate("MainWindow", "<html><head/><body><p>x<span style=\" vertical-align:sub;\">min</span></p></body></html>"))
        self.label_25.setText(_translate("MainWindow", "<html><head/><body><p>y<span style=\" vertical-align:sub;\">min</span></p></body></html>"))
        self.label_27.setText(_translate("MainWindow", "<html><head/><body><p>z<span style=\" vertical-align:sub;\">min</span></p></body></html>"))
        self.label_24.setText(_translate("MainWindow", "<html><head/><body><p>x<span style=\" vertical-align:sub;\">max</span></p></body></html>"))
        self.label_26.setText(_translate("MainWindow", "<html><head/><body><p>y<span style=\" vertical-align:sub;\">max</span></p></body></html>"))
        self.label_28.setText(_translate("MainWindow", "<html><head/><body><p>z<span style=\" vertical-align:sub;\">max</span></p></body></html>"))
        self.pushButton_loadScenario.setText(_translate("MainWindow", "Load scenario"))
        self.pushButton_launchAnimation.setText(_translate("MainWindow", "Launch animation"))
        self.pushButton_launchCharts.setText(_translate("MainWindow", "Launch charts"))
        self.lineEdit_saveAnimationFilename.setPlaceholderText(_translate("MainWindow", "filename"))
        self.pushButton_saveAnimation.setText(_translate("MainWindow", "Save animation"))
        self.lineEdit_saveTrajectoryFilename.setPlaceholderText(_translate("MainWindow", "filename"))
        self.pushButton_saveTrajectory.setText(_translate("MainWindow", "Save trajectory"))
        self.label_Status.setText(_translate("MainWindow", "Status: "))
        self.menuJobs.setTitle(_translate("MainWindow", "Options"))
        self.actionEdit_List.setText(_translate("MainWindow", "Save Session"))
        self.actionLaunch.setText(_translate("MainWindow", "Launch"))
        self.actionLaunch_List.setText(_translate("MainWindow", "Launch Session"))
        self.actionEdit_Job.setText(_translate("MainWindow", "New Job"))
        self.actionLaunch_Job.setText(_translate("MainWindow", "Launch Job"))
        self.actionTemplate_Path.setText(_translate("MainWindow", "Template Path"))
        self.actionShow_Hide_Video_Window.setText(_translate("MainWindow", "Show/Hide Video Window"))
        self.actionlocal_mode.setText(_translate("MainWindow", "local dataserver mode"))
        self.actionNew_Session.setText(_translate("MainWindow", "New Session..."))
        self.actionNew_Session.setIconText(_translate("MainWindow", "New Session..."))
        self.actionNew_Session.setToolTip(_translate("MainWindow", "New Session..."))
        self.actionOpen_Session.setText(_translate("MainWindow", "Open Session"))
        self.actionSave_Session_As.setText(_translate("MainWindow", "Save Session As..."))
        self.actionSave_Session_As.setIconText(_translate("MainWindow", "Save Session As..."))
        self.actionSave_Session_As.setToolTip(_translate("MainWindow", "Save Session As..."))
        self.actionPath_Root.setText(_translate("MainWindow", "Path Root"))
        self.actionSession_Manager.setText(_translate("MainWindow", "Session Manager"))
        self.actionChange_lidar_file.setText(_translate("MainWindow", "Change lidar file"))
        self.actionChange_save_folder.setText(_translate("MainWindow", "Change save folder"))
        self.actionViewing_parameters.setText(_translate("MainWindow", "Viewing parameters"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
